### PR TITLE
ZEN-13939: Restrict multiselect component to display options in one line

### PR DESCRIPTION
**Pull request by gregorojstersek**
[Jira ticket](https://reciprocitylabs.atlassian.net/browse/ZEN-13939)

### Before

Screenshot 2020-03-16 at 10 13 18

Screenshot 2020-03-16 at 10 21 29

### After

Screenshot 2020-03-16 at 10 26 34
Screenshot 2020-03-16 at 10 26 47

### CODE REVIEW

**Comment by mplesec** [comment]
This was ok'd by designers right?

**Comment by zenbot-0** [comment]
🔬 [Click here](https://reciprocity.github.io/zenlib/branches/truncate-multiselect-labels) to test your changes on Storybook

**Comment by gregorojstersek** [comment]
@mplesec Yes, discussed with Igor.

**Comment by leferreyra** [comment]
@gregorojstersek I'd be cool to add a new story with long options, that's up to you though

**Pull request merged**
