### PR TITLE
ZEN-15222: add search icon to the multiselect search field

### PR DESCRIPTION
**Pull request by leferreyra**
https://reciprocitylabs.atlassian.net/browse/ZEN-15222

Adds a search icon to the multiselect search field.

Screen Shot 2020-05-28 at 09 44 59

### CODE REVIEW

**Comment by zenbot-0** [comment]
🔬 [Click here](https://reciprocity.github.io/zenlib/branches/multiselect-search-icon) to test your changes on Storybook

**Comment by chavlji** [comment]
Looks nice!

Just two things I've noticed:
- there's no search icon in the input on single-selects
- there's no search icon in the input on multi-selects with prop `search-in-dropdown` set to `false` (Although there's currently no such element in the zengrc)

If the above is ok, we can merge it!

**Comment by leferreyra** [comment]
@chavlji those are good questions. I'll ask Mary about that, it wasn't really a requirement. I'd do that in a different issue anyways. Thanks!

**Comment by chavlji** [comment]
Top! Then just please rebase and we can merge it!

**Pull request merged**
